spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shortenurl?characterEncoding=utf-8
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml