spring:
  datasource:
    url: jdbc:mysql://82.157.161.170:3306/shorturl?characterEncoding=utf-8
    username: root
    password: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml